/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viggenere;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author demon
 */
public class InterfazKawaii extends javax.swing.JFrame {

    /**
     * Creates new form InterfazKawaii
     */
    public InterfazKawaii() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        far = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Cifrar = new javax.swing.JButton();
        Descifrar = new javax.swing.JButton();
        mj = new javax.swing.JTextField();
        res = new javax.swing.JTextField();
        Cifrar1 = new javax.swing.JButton();
        cam = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(177, 222, 231));
        jPanel1.setLayout(null);

        far.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                farActionPerformed(evt);
            }
        });
        jPanel1.add(far);
        far.setBounds(60, 50, 270, 20);

        jLabel1.setText("Mensaje");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 11, 80, 14);

        jLabel2.setText("Palabra");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 50, 70, 14);

        Cifrar.setText("Cifrar");
        Cifrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CifrarActionPerformed(evt);
            }
        });
        jPanel1.add(Cifrar);
        Cifrar.setBounds(10, 80, 100, 23);

        Descifrar.setText("Descifrar");
        Descifrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescifrarActionPerformed(evt);
            }
        });
        jPanel1.add(Descifrar);
        Descifrar.setBounds(130, 80, 100, 23);

        mj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mjActionPerformed(evt);
            }
        });
        jPanel1.add(mj);
        mj.setBounds(60, 10, 270, 30);

        res.setEnabled(false);
        res.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resActionPerformed(evt);
            }
        });
        jPanel1.add(res);
        res.setBounds(10, 210, 320, 50);

        Cifrar1.setText("Cifrar");
        Cifrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cifrar1ActionPerformed(evt);
            }
        });
        jPanel1.add(Cifrar1);
        Cifrar1.setBounds(10, 80, 59, 23);

        cam.setText("Cambiar");
        cam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                camActionPerformed(evt);
            }
        });
        jPanel1.add(cam);
        cam.setBounds(241, 80, 90, 23);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viggenere/img/neko.jpg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 340, 270);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    private void mjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mjActionPerformed
                
    }//GEN-LAST:event_mjActionPerformed

    private void farActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_farActionPerformed
       
    }//GEN-LAST:event_farActionPerformed

    private void resActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resActionPerformed
      
    }//GEN-LAST:event_resActionPerformed

    private void CifrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CifrarActionPerformed
       
    Vigikawaii obj = new Vigikawaii();
    
    String textoclaro = mj.getText().toUpperCase();
    String clave = far.getText().toUpperCase();
    
    if (textoclaro.isEmpty() || clave.isEmpty()){
        JOptionPane.showMessageDialog(null,"Llene los campos para continuar");
    }else{
        Pattern p = Pattern.compile("[A-Za-z].*");
        Matcher txt = p.matcher(textoclaro);
        Matcher cla = p.matcher(clave);
   
            if(txt.matches()==true && cla.matches()==true) { 
                if(textoclaro.length() > clave.length()){
                    String resul = obj.encriptarTextoClaro(textoclaro.replace(" ", ""), clave.replace(" ", ""));
                    res.setText(resul);
                }else{
                    JOptionPane.showMessageDialog(null,"La clave debe ser mas pequeña que el mensaje");  
                } 
               
            }else{
                JOptionPane.showMessageDialog(null,"No se aceptan caracteres especiales");  
            }
      
    } 
    
    
    
    }//GEN-LAST:event_CifrarActionPerformed

    private void DescifrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescifrarActionPerformed
    Vigikawaii obj = new Vigikawaii();
    
    String textoclaro = mj.getText().toUpperCase();
    String clave = far.getText().toUpperCase(); 
    
    if (textoclaro.isEmpty() || clave.isEmpty()){
        JOptionPane.showMessageDialog(null,"Llene los campos para continuar");
    }else{  
        Pattern p = Pattern.compile("[A-Za-z].*");
        Matcher txt = p.matcher(textoclaro);
        Matcher cla = p.matcher(clave);
        if(txt.matches()==true && cla.matches()==true) { 
            if(textoclaro.length() > clave.length()){
                String resul = obj.desencriptarTextoClaro(textoclaro.replace(" ", ""), clave.replace(" ", ""));
                res.setText(resul);
            }else{
                JOptionPane.showMessageDialog(null,"La clave debe ser mas pequeña que el mensaje");  
            }    
        }else{
            JOptionPane.showMessageDialog(null,"No se aceptan caracteres especiales");  
        }
        
    }
    
    }//GEN-LAST:event_DescifrarActionPerformed

    private void Cifrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cifrar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cifrar1ActionPerformed

    private void camActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_camActionPerformed
        String one = mj.getText();
        String two = res.getText();
        
        mj.setText(two);
        res.setText(one);
        
    }//GEN-LAST:event_camActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazKawaii.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazKawaii.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazKawaii.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazKawaii.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazKawaii().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cifrar;
    private javax.swing.JButton Cifrar1;
    private javax.swing.JButton Descifrar;
    private javax.swing.JButton cam;
    private javax.swing.JTextField far;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField mj;
    private javax.swing.JTextField res;
    // End of variables declaration//GEN-END:variables

}
